### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/jelly-beats#266]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

### Todo

- [x] Create profile page.
- [x] Store channel data on cache.
- [x] Load channel data from cache.
- [x] Load extended metadata for channels ( profile ).
- [ ] Channel time line ( activity tracker, feed ).
